// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbx4dwlubfTA8a7f2mDJfVcPn191HMgBc',
    appId: '1:669897459657:web:6bb82a5f0746fa4ff44a18',
    messagingSenderId: '669897459657',
    projectId: 'assistly-29a43',
    authDomain: 'assistly-29a43.firebaseapp.com',
    storageBucket: 'assistly-29a43.appspot.com',
    measurementId: 'G-ZBVQH53BMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGAHC-JEweJPNWtWU7uvn1tuDebETUb3o',
    appId: '1:669897459657:android:0263faaf00b8990ff44a18',
    messagingSenderId: '669897459657',
    projectId: 'assistly-29a43',
    storageBucket: 'assistly-29a43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUcAN4Qd6psWrfwLcSzISqEbOBNQDSAec',
    appId: '1:669897459657:ios:27a2215aae88462af44a18',
    messagingSenderId: '669897459657',
    projectId: 'assistly-29a43',
    storageBucket: 'assistly-29a43.appspot.com',
    iosBundleId: 'com.example.assistlyPersonalAiAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUcAN4Qd6psWrfwLcSzISqEbOBNQDSAec',
    appId: '1:669897459657:ios:27a2215aae88462af44a18',
    messagingSenderId: '669897459657',
    projectId: 'assistly-29a43',
    storageBucket: 'assistly-29a43.appspot.com',
    iosBundleId: 'com.example.assistlyPersonalAiAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbx4dwlubfTA8a7f2mDJfVcPn191HMgBc',
    appId: '1:669897459657:web:bdb6363ca4ac8d5af44a18',
    messagingSenderId: '669897459657',
    projectId: 'assistly-29a43',
    authDomain: 'assistly-29a43.firebaseapp.com',
    storageBucket: 'assistly-29a43.appspot.com',
    measurementId: 'G-ZF7XTZ6R0Y',
  );

}